# m4-loan-evaluation-service-deployment-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m4-loan-evaluation-service-deployment
  labels:
    app: m4-loan-evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m4-loan-evaluation-service
  template:
    metadata:
      labels:
        app: m4-loan-evaluation-service
    spec:
      containers:
        - name: m4-loan-evaluation
          image: xsh1ft/m4-loan-evaluation-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server-service:8888"
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "true"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info"
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              value: "always"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: m4-loan-evaluation-service
  labels:
    app: m4-loan-evaluation-service
spec:
  selector:
    app: m4-loan-evaluation-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP