# mysql-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  DB_USER_M2: dXNlcg==        # "user"
  DB_PASSWORD_M2: cGFzc3dvcmQ= # "password"
  DB_USER_M3: dXNlcg==
  DB_PASSWORD_M3: cGFzc3dvcmQ=
